[package]
name = "rusty_chip_eight"
version = "0.1.0"
authors = ["Eduard Ilin <ei2@ukrosoft.com.ua>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
